### ISSUE TITLE
Halcyon breaks if ~/.ghc is present

### ISSUE THREAD

**Issue by pbrisbin** [mietek/halcyon#5] opened 2015-01-07 00:15 UTC
Here's the script I'm running to try and build a local project using halcyon:

```sh
#!/bin/bash
set -e

builddir="$HOME/halcyon-build"

#mkdir -p "$builddir"
#git clone https://github.com/mietek/halcyon.git "$builddir/halcyon"

export HALCYON_BASE="$builddir"
export HALCYON_PREFIX="$builddir"
export HALCYON_NO_SELF_UPDATE=1

export HALCYON_AWS_ACCESS_KEY_ID='x'
export HALCYON_AWS_SECRET_ACCESS_KEY='x'
export HALCYON_S3_BUCKET='x'

source <( "$builddir/halcyon/halcyon" paths )

halcyon build
```

The script is being run from within the project root.

GHC and Cabal installed OK, but it failed on the first extra app, alex:

```
-----> Installing carnival-0.0.0
-----> Determining constraints
       Label:                                    carnival-0.0.0
       Prefix:                                   /home/patrick/code/carnival/halcyon-build
       Source hash:                              813f5e7
       Constraints hash:                         b829d67
       Magic hash:                               2528ea3
       External storage:                         private and public
       GHC version:                              7.8.3
       Cabal version:                            1.22.0.0
       Cabal repository:                         Hackage
       Sandbox magic hash:                       c0b8c0e
       Sandbox extra apps:                       alex-3.1.3
                                                 happy-1.19.4

-----> Using existing GHC

-----> Using existing Cabal directory
   *** WARNING: Unexpected existing Cabal config
   *** WARNING: To replace with recommended Cabal config:
       $ ln -fs /home/patrick/code/carnival/halcyon-build/cabal/.halcyon-cabal.config ~/.cabal/config

-----> Restoring sandbox directory
       Downloading s3://thoughtbot-haskell-packages/linux-arch-x86_64/ghc-7.8.3/halcyon-sandbox-b829d67.c0b8c0e-carnival-0.0.0.tar.gz... 404 (not found)
       Downloading https://halcyon.global.ssl.fastly.net/linux-arch-x86_64/ghc-7.8.3/halcyon-sandbox-b829d67.c0b8c0e-carnival-0.0.0.tar.gz... 404 (not found)
-----> Locating sandbox directories
       Listing s3://thoughtbot-haskell-packages/?prefix=linux-arch-x86_64/ghc-7.8.3/halcyon-sandbox-... done
       Listing https://halcyon.global.ssl.fastly.net/... done
-----> Building sandbox directory
-----> Creating sandbox
-----> Installing sandbox extra apps
       -----> Unpacking app
       -----> Installing alex-3.1.3
       -----> Determining constraints
          *** WARNING: Using newest versions of all packages
              QuickCheck-2.7.6
              array-0.5.0.0
              base-4.7.0.1
              bytestring-0.10.4.0
              containers-0.5.5.1
              deepseq-1.3.0.2
              directory-1.2.1.0
              filepath-1.3.0.2
              ghc-prim-0.3.1.0
              integer-gmp-0.5.1.0
              old-locale-1.0.0.6
              pretty-1.1.1.1
              primitive-0.5.4.0
              random-1.1
              rts-1.0
              template-haskell-2.9.0.0
              tf-random-0.5
              time-1.4.2
              transformers-0.3.0.0
              unix-2.7.0.1
       
              Label:                                    alex-3.1.3
              Prefix:                                   /home/patrick/code/carnival/halcyon-build/sandbox
              Source hash:                              86b14de
              GHC version:                              7.8.3
              External storage:                         private and public
       
       -----> Restoring install directory
              Downloading s3://thoughtbot-haskell-packages/linux-arch-x86_64/ghc-7.8.3/halcyon-install-86b14de-alex-3.1.3.tar.gz... 404 (not found)
              Downloading https://halcyon.global.ssl.fastly.net/linux-arch-x86_64/ghc-7.8.3/halcyon-install-86b14de-alex-3.1.3.tar.gz... 404 (not found)
       
              Label:                                    alex-3.1.3
              Prefix:                                   /home/patrick/code/carnival/halcyon-build/sandbox
              Source hash:                              86b14de
              Constraints hash:                         9d915b2
              External storage:                         private and public
              GHC version:                              7.8.3
              Cabal version:                            1.22.0.0
              Cabal repository:                         Hackage
       
       -----> Restoring sandbox directory
              Extracting halcyon-sandbox-9d915b2-alex-3.1.3.tar.gz... done, 7.3MB
       
       -----> Restoring build directory
              Downloading s3://thoughtbot-haskell-packages/linux-arch-x86_64/ghc-7.8.3/halcyon-build-alex-3.1.3.tar.gz... 404 (not found)
              Downloading https://halcyon.global.ssl.fastly.net/linux-arch-x86_64/ghc-7.8.3/halcyon-build-alex-3.1.3.tar.gz... 404 (not found)
       -----> Configuring app
              Using a sandbox located at /home/patrick/code/carnival/halcyon-build/sandbox
              /home/patrick/code/carnival/halcyon-build/ghc/bin/ghc --numeric-version
              looking for tool ghc-pkg near compiler in
              /home/patrick/code/carnival/halcyon-build/ghc/bin
              found ghc-pkg in /home/patrick/code/carnival/halcyon-build/ghc/bin/ghc-pkg
              /home/patrick/code/carnival/halcyon-build/ghc/bin/ghc-pkg --version
              /home/patrick/code/carnival/halcyon-build/ghc/bin/ghc --supported-languages
              /home/patrick/code/carnival/halcyon-build/ghc/bin/ghc --info
              Reading available packages...
              Choosing modular solver.
              Resolving dependencies...
              creating dist/setup
              /home/patrick/code/carnival/halcyon-build/ghc/bin/ghc --make -odir ./dist/setup -hidir ./dist/setup -i -i. -package-db /home/patrick/code/carnival/halcyon-build/sandbox/x86_64-linux-ghc-7.8.3-packages.conf.d -package-id Cabal-1.20.0.2-842e7912fac8797e77f21298825e4931 ./dist/setup/setup.hs -o ./dist/setup/setup -threaded
              <command line>: cannot satisfy -package-id Cabal-1.20.0.2-842e7912fac8797e77f21298825e4931: 
                  Cabal-1.20.0.2-842e7912fac8797e77f21298825e4931 is unusable due to missing or recursive dependencies:
                    array-0.5.0.0-98aa445e59f3eb0c886795ff07406d84 base-4.7.0.1-e4b74d27ad8c8987c63abc42a80e7335 bytestring-0.10.4.0-9f46be651278ecf2e2b21a220bfff6bf containers-0.5.5.1-23e2a2b94d6e452c773209f31d8672c5 deepseq-1.3.0.2-733fe43e121f761739636bd6670bea77 directory-1.2.1.0-4c475f14fe8252aac085a98bf26e5baf process-1.2.0.0-163b32a503548d746f4aa93b497ff8ea time-1.4.2-bf925e935c287d0b75398fe297453c28 unix-2.7.0.1-0d8e7ccf059d972d7aad20e259a6e218
                  (use -v for more information)
          *** ERROR: Failed to configure app
   *** WARNING: Cannot install sandbox extra apps
   *** WARNING: Cannot build sandbox directory
   *** WARNING: Cannot install app

shell returned 1
```

When I `mv ~/.ghc ~/ghc.bak`, the problem went away and the build proceeded.

**Comment by mietek** [comment] 2015-01-07 01:09
Can you try redoing this with `--cabal-version=1.20.0.3`?

**Comment by pbrisbin** [comment] 2015-01-30 17:09
We discovered in IRC that the issue is bootstrapping Cabal with a `~/.ghc` present. Builds using a cached Cabal directory are fine even when `~/.ghc` is present.

**Comment by mietek** [comment] 2015-01-30 17:31
I did think so at the time, but then I recalled Halcyon already points `HOME` to a temporary directory when bootstrapping Cabal (https://github.com/mietek/halcyon/blob/master/src/cabal.sh#L314).

Do you have a way to reproduce this issue?

**Comment by pbrisbin** [comment] 2015-01-30 18:12
> Do you have a way to reproduce this issue?

I would guess that if I trigger a from-scratch build without moving my `~/.ghc` it'll still happen. Let me try.

**Comment by pbrisbin** [comment] 2015-01-30 20:25
I'm not sure how to trigger a from-scratch rebuild. Here's the log when passing ` --ghc-rebuild --cabal-rebuild --sandbox-rebuild --app-rebuild`:

http://sprunge.us/edPR

It didn't seem to rebuild alex/happy, which is where this error occurred before. It did rebuild yesod-bin and failed for what looks like a different reason.

**Comment by mietek** [comment] 2015-01-30 20:55
With regard to rebuilding _alex_ or _happy_ — you should be able to do it by purging your local cache (either manually, or with `--purge-cache`), and preventing the previously-built archives from being downloaded (with `--no-public-storage` and `--no-private-storage`).

Now, this new failure looks really odd, and possibly related to what we were talking about earlier:
```
-----> Building sandbox
       cabal: The package environment file '/app/sandbox/cabal.sandbox.config'
       doesn't exist
   *** ERROR: Failed to build sandbox
```

I’m looking into it right now.

**Comment by pbrisbin** [comment] 2015-01-30 22:25
I can't seem to trigger it to rebuild alex or happy. I `rm -rf /tmp/halcyon*`, pass all those rebuild flags, and add `--purge-cache --no-public-storage --no-private-storage`. Log: http://sprunge.us/CCGM

**Comment by mietek** [comment] 2015-01-30 23:17
I don’t see "Purging cache" in the log, and it really should be there:
https://github.com/mietek/halcyon/blob/master/src/storage.sh#L334

Can you include your command-line in the logs you paste, please?  What was the command-line you just used?

**Comment by pbrisbin** [comment] 2015-01-30 23:55
I won't be able to try for a few days, but next time I'll log with
something like bash -x so you can see it all.

**Comment by mietek** [comment] 2015-01-31 00:06
That’ll be far too much info, thanks. I’m just pretty sure your cache still contains some files:
```
       -----> Restoring install directory
              Extracting halcyon-install-86b14de-alex-3.1.3.tar.gz... done, 2.4MB
```
```
       -----> Restoring install directory
              Extracting halcyon-install-c4bf010-happy-1.19.4.tar.gz... done, 2.0MB
```

**Comment by mietek** [comment] 2015-01-31 19:18
@pbrisbin I can’t reproduce the [original issue](https://github.com/mietek/halcyon/issues/5#issue-53581156).

I have, however, identified a related issue (https://github.com/haskell/cabal/issues/2400). It appears sandboxes cannot be trusted to isolate the user from the contents of `~/.ghc` while performing `cabal install`.

**Comment by mietek** [comment] 2015-02-02 00:16
@pbrisbin I’m sorry, but I can’t reproduce the [new issue](https://github.com/mietek/halcyon/issues/5#issuecomment-72264836), either. It’d be great if you could provide step-by-step reproduction instructions, starting with a fresh system.

**Comment by mietek** [comment] 2015-02-02 00:32
With https://github.com/mietek/halcyon/commit/a7e68519e8ea305da16f8bff50eb7c8740e913a9, Halcyon will now refuse to run if anything except `~/.ghc/ghci_history` is present in `~/.ghc`.

**Comment by pbrisbin** [comment] 2015-02-02 15:49
> With a7e6851, Halcyon will now refuse to run if anything except ghci_history is present in ~/.ghc.

Well that's very unfortunate. Halcyon gets much less attractive for local development if it can't co-exist with a normal setup. Also, if you can't reliably reproduce the issue anyway, why the pre-emptive workaround?

With that change in place, I can't test this theory easily, but I think the error occurs when the version of Cabal build by Halcyon differs from the one on the machine. In my case, 1.20 was still installed and Halcyon was using 1.22 by default at the time.

> It’d be great if you could provide step-by-step reproduction instructions, starting with a fresh system

I assume you mean the new issue? I won't be able to do the legwork of a clean VM for a while, but here is a log that includes the commands I'm running at least:

Repro script: http://sprunge.us/SfJC?sh
Log: http://sprunge.us/CSWA?log

Here you can see it fails on the first sandbox extra app.

I'm re-running now with the default 1.20 to see if it's a 1.22 issue.

**Comment by mietek** [comment] 2015-02-03 06:56
There are three issues mentioned in this thread:

1. The [original issue](https://github.com/mietek/halcyon/issues/5#issue-53581156), in which installing `alex-3.1.3` fails at configure time, which I can’t reproduce
2. The [new issue](https://github.com/mietek/halcyon/issues/5#issuecomment-72264836), in which building sandbox fails due to missing `/app/sandbox/cabal.sandbox.config`, which I can’t reproduce
3. The issue of `cabal install` breaking sandbox isolation, which I _can_ reproduce, and which I’ve reported as https://github.com/haskell/cabal/issues/2400

It’s issue number 3 which makes the latest workaround necessary.

With https://github.com/mietek/halcyon/commit/0ac700e22733b2fefcd43a6bf67b61f9a67a7623, you can now force Halcyon to revert to the original behaviour and tolerate a non-empty `~/.ghc` by setting `HALCYON_INTERNAL_TOLERATE_GHC_USER_DB=1`.

Did you know you can get a new VM set up on DigitalOcean in 55 seconds?  It’s what I do to test Halcyon, and what I’ve been doing for the past two days, trying to reproduce issues number 1 and 2.

**Comment by mietek** [comment] 2015-02-03 07:08
@pbrisbin At least one mystery is now solved https://github.com/mietek/halcyon/commit/91d3157197cf09420e6ff219e5ac1e8e3c9f9d66, thanks to your repro script — the `build` command wasn’t allowing the cache to be cleaned, because the `build` command is an afterthought.

**Comment by pbrisbin** [comment] 2015-02-03 13:57
OK. I'm re-running now in an attempt to trigger Issue 1. If it doesn't, we should close this.

Issue 2, I have to assume, is because Halcyon is finding/using old archives that don't have that file. Even with the bug you fixed in `build`, I was manually `rm -rf /tmp/halcyon*` so I can't see where it's getting them (and only some of them) from. Anyway -- if this also doesn't reproduce since your last fix, we should ignore that issue for now as well. If it does reproduce, I'll open a new Issue and see if I can get you a reproducing VM/VPS to inspect.

Issue 3, it seems is already addressed by your `~/.ghc` workaround.

Will let you know once the build finishes.

**Comment by pbrisbin** [comment] 2015-02-03 15:39
Well. I can't reproduce issues 1, 2, or 3. But I get a new one (of course):

```
cabal: dist/package.conf.inplace: inappropriate type
```

Here's the full log: http://sprunge.us/iTYL?log

Notes:

- This is the same repro script
- This is using the default 1.20
- I have 1.22 installed in my user db, BUT
- This occurs **with or without** `~/.ghc` present
- With your latest fix, it is actually rebuilding everything from scratch
- I've gotten this before, when using an archive built for a different version of Cabal (remember we discussed a bit about using the Cabal version in the archive hash key?) -- this doesn't appear to be that, but it's the same exact error

Should I open a new Issue?

**Comment by mietek** [comment] 2015-02-03 15:54
> Even with the bug you fixed in build, I was manually rm -rf /tmp/halcyon* so I can't see where it's getting them (and only some of them) from. 

The default location for [`HALCYON_CACHE`](https://halcyon.sh/reference/#halcyon_cache) is `/var/tmp/halcyon-cache`.

**Comment by pbrisbin** [comment] 2015-02-03 15:55
Ha, well that explains that

**Comment by mietek** [comment] 2015-02-03 15:57
Do you have any files in the `dist` directory committed to your source repository?

**Comment by pbrisbin** [comment] 2015-02-03 15:58
Shit. Not committed, but they are there. Let me run again after removing that.

**Comment by mietek** [comment] 2015-02-03 21:25
OK. I’m not satisfied that we were unable to find an exact cause for these issues, but I think we have a fairly good explanation — somehow, a sandbox archive with a bad or missing `cabal.sandbox.config` was uploaded to private storage. Once there, it kept getting restored, due to a bug with `build`, and a misunderstanding of the cache location.

Thanks for working towards a solution together, @pbrisbin.

**Closed by mietek** 2015-02-03 21:25 UTC
Labels: bug
